### ISSUE TITLE
Model_best.pth.tar is corrupted/damaged file

### ISSUE THREAD

**Issue by qazi876** [wondonghyeon/protest-detection-violence-estimation#3]

**Comment by qazi876** [comment]
its not working how to find

**Comment by dexception** [comment]
+1

**Comment by dee6600** [comment]
python pred.py --img_dir img/ --output_csvpath result.csv --model model_best.pth.tar --cuda
*** loading model from model_best.pth.tar
Traceback (most recent call last):
  File "pred.py", line 116, in <module>
    main()
  File "pred.py", line 72, in main
    model.load_state_dict(torch.load(f)['state_dict'])
  File "C:\Users\dee\Anaconda3\lib\site-packages\torch\serialization.py", line 426, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\dee\Anaconda3\lib\site-packages\torch\serialization.py", line 595, in _load
    return legacy_load(f)
  File "C:\Users\dee\Anaconda3\lib\site-packages\torch\serialization.py", line 506, in legacy_load
    with closing(tarfile.open(fileobj=f, mode='r:', format=tarfile.PAX_FORMAT)) as tar, \
  File "C:\Users\dee\Anaconda3\lib\tarfile.py", line 1591, in open
    return func(name, filemode, fileobj, **kwargs)
  File "C:\Users\dee\Anaconda3\lib\tarfile.py", line 1621, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "C:\Users\dee\Anaconda3\lib\tarfile.py", line 1484, in __init__
    self.firstmember = self.next()
  File "C:\Users\dee\Anaconda3\lib\tarfile.py", line 2289, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "C:\Users\dee\Anaconda3\lib\tarfile.py", line 1094, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "C:\Users\dee\Anaconda3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 338: character maps to <undefined>



not working !!!

**Comment by dexception** [comment]
I am able to run it on ubuntu 16.04, cuda 9.0, cudnn 7.0.5, python2
